### ISSUE TITLE
It's not compatible with Python 2.6

### ISSUE THREAD

**Issue by luisjaviersanz** [ncbi/robotframework-pageobjects#21]
robotframework-pageobjects is not compatible with Python 2.6, while RobotFramework it is. So, it's not possible to use them together in this version. (It would be awesome!).

```bash
Ghost:/robot/src# python --version
Python 2.6.6

Ghost:/robot/src# python -c "import robot"    # OK
Ghost:/robot/src# python -c "import robotpageobjects"    # IT FAILS!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/stuff/core/lib/python2.6/site-packages/robotpageobjects/__init__.py", line 1, in <module>
    from .base import Override, robot_alias, not_keyword
  File "/usr/share/stuff/core/lib/python2.6/site-packages/robotpageobjects/base.py", line 15, in <module>
    from . import abstractedlogger
  File "/usr/share/stuff/core/lib/python2.6/site-packages/robotpageobjects/abstractedlogger.py", line 103
    inv_translation_map = {v: k for k, v in translation_map.items()}
                                  ^
SyntaxError: invalid syntax
Ghost:/robot/src#
```

**Comment by kahunacohen** [comment]
It would be awesome. However we have to balance our organization's priorities with our willingness to open source this project. We run Python 2.7x and so we're not in a position to spend time "fixing" this.

You're welcome to take a look and issue a pull request. You could use a virtual environment for this and specify Python 2.7:

```
$ virtualenv -p python2.7 env
$ . env/bin/activate
$ pip install robotframework-pageobjects
```
I'll update the README to specify what this has been tested in.

**Comment by luisjaviersanz** [comment]
Thanks, @kahunacohen! I'll check it out in my spare time.

**Comment by kahunacohen** [comment]
Closing due to inactivity. Please open if you want to make this change.
